### ISSUE TITLE
Code Availability Inquiry for Experiments: MCM with CoOp/CoCoOp and LSN's Positive Prompt with LoCoOp

### ISSUE THREAD

**Issue by JB0527** [AtsuMiyai/LoCoOp#5]
Hello, I'm currently reading through papers and accompanying code. First of all, thank you for helping me conduct some great experiments!

However, after reviewing the citation you provided, I would like to inquire about whether there are separate codes available for conducting experiments with 'MCM+CoOp' or 'MCM+CoCoOp' as mentioned in 1. Additionally, I came across an openreview stating that using LSN's positive prompt with LoCoOp yielded good results ('Learn to say no + LoCoOP' as in 2). Is there code available for the experiments conducted in these cases?

Thank you.

> 
> 
> Subsequent work for Parameter-Efficient OOD detection methods
> Parameter-efficient OOD detection is a promising research direction, and LoCoOp can be a baseline approach for this field.
> To catch up with this field, we summarized the subsequent work for CLIP-based efficient OOD detection methods. (Last update: 2024.04.14)
> 
> , [code](https://github.com/deeplearning-wisc/MCM)
> This is the journal extension version of [MCM](https://proceedings.neurips.cc/paper_files/paper/2022/hash/e43a33994a28f746dcfd53eb51ed3c2d-Abstract-Conference.html). This paper examines the effectiveness of MCM with vanilla prompt learning methods (e.g., CoOp). To implement this, you can utilize our LoCoOp's code following https://github.com/AtsuMiyai/LoCoOp/issues/2#issuecomment-1923390359.
> 
> 
> LSN learns negative prompts for OOD detection, which is an orthogonal approach to LoCoOp and [can be combined with LoCoOp](https://openreview.net/forum?id=nanyAujl6e&referrer=%5Bthe%20profile%20of%20Jun%20Nie%5D(%2Fprofile%3Fid%3D~Jun_Nie1)).
> 
> , [code](https://github.com/ycfate/ID-like)
> IDPrompt leverages ID-like outliers in the ID image to further leverage the capabilities of CLIP for OOD detection, which is a similar concept to LoCoOp.
> 
> , [code](https://github.com/LuFan31/LSA)
> LSA first tackled [full-spectrum OOD detection](https://arxiv.org/abs/2204.05306) in the context of CLIP-based parameter-efficient OOD detection.
> 
> , [code](https://github.com/mala-lab/negprompt)
> NegPrompt learns a set of negative prompts with only ID data. Also, this paper tackled a novel promising problem setting called Open-vocabulary OOD detection.
> 
> If I missed some work, feel free to contact me by opening an issue!

**Comment by AtsuMiyai** [comment]
@JB0527 Hi! Thanks for your interest! 

My answers are as follows:

1.  For MCM+CoOp,  you can comment out  like #  + self.lambda_value * loss_en in https://github.com/AtsuMiyai/LoCoOp/blob/master/trainers/locoop.py#L299 (or in https://github.com/AtsuMiyai/LoCoOp/blob/master/trainers/locoop.py#L317)
For  'MCM+CoCoOp', we do not provide the code, but I think you can easily write the code for MCM+CoCoOp because MCM is really simple.


 2. We do not provide the code with LoCoOp + LSN. If you want it, could you please contact the author of LSN?  Also, since LoCoOp+LSN is a rebuttal experiment, I think you do not need to include it as a comparison method in your paper.

**Comment by AtsuMiyai** [comment]
Did you solve this problem? 

I will close this issue, but if you have another question, please feel free to open this!
